repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10
    hooks:
      - id: ruff
        args: ["--fix"]
        stages: [pre-commit]
        types: [python]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        args: ["-q", "-r", "src", "-x", "tests"]
        pass_filenames: false
        # Bandit remains non-blocking for now. Use fail_fast: false to gather
        # all issues; developers must fix or # nosec touched files.
  - repo: local
    hooks:
      - id: pytest
        name: pytest quick
        entry: >-
          bash -c 'if [[ -n "$SKIP_TEST_HOOKS" ]]; then exit 0; fi;
          export PYTEST_ADDOPTS="";
          pytest -q --maxfail=1 -p no:cacheprovider'
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: mypy-advisory
        name: mypy (advisory)
        entry: bash -c 'mypy src || true'
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: mkdocs-build
        name: mkdocs strict build
        entry: mkdocs build --strict
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: git-status-clean
        name: ensure-no-untracked-files
        entry: bash -c 'if [[ -n "$SKIP_GIT_CLEAN" ]]; then exit 0; fi; [[ -z $(git ls-files --others --exclude-standard) ]] || (echo "⚠️  Untracked files present. Run \"git add -A\"." && exit 1)'
        language: system
        pass_filenames: false
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.23
    hooks:
      - id: actionlint 