site_name: agent_system Documentation
site_url: https://ianlucas1.github.io/agent_system/
repo_url: https://github.com/ianlucas1/agent_system/
edit_uri: edit/main/

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Multi-Agent How-To: multi_agent.md
  - CLI & GitOps: cli_gitops.md
  - Quality Policy: quality_policy.md
  - API Reference: api_reference.md

theme:
  name: material
  features:
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy

plugins:
  - mermaid2 