name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt
          python -m pip install -e .
      - name: Ruff
        run: ruff check .
      - name: Mypy (non-blocking)
        run: mypy src || true
      - name: Bandit
        run: bandit -q -r src
      - name: Tests & Coverage
        run: |-
          pytest -q
          coverage xml
      - name: Build Docs
        run: mkdocs build --strict
      - name: Ensure repo clean (no untracked files)
        run: |
          git status --porcelain
          test "$(git status --porcelain | wc -l)" -eq 0 